### ISSUE TITLE
Writing the service broker in .NEt core using EF

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/meta-azure-service-broker#121]
Hi,
Will it be possible to write the broker in .NET core using the SDk
https://github.com/hpcloud/stackato-dotnet-sdk
By that we can make the SDK database independent using EF core. Please suggest.

**Comment by zhongyi-zhang** [comment]
Hi, 
I think writing a broker in .NET core is ok but there is no need to use the SDK.
The broker doesn't need to call CC API. It is that CC calls the broker API.
What a broker need is to implement the broker APIs. Please refer: https://docs.cloudfoundry.org/services/api.html
