### ISSUE TITLE
No tag for 1.4.0

### ISSUE THREAD

**Issue by mrbuk** [Azure/meta-azure-service-broker#134]
I do see in https://docs.pivotal.io/partners/azure-sb/release-notes.html that version 1.4.0 was released. Unfortunately I don't find the corresponding tag in GH.

I would be interessted if the following change in master made it to 1.4.0:

* [Bug in 1.3.0](https://github.com/Azure/meta-azure-service-broker/blob/v1.3.0/lib/services/azuremysqldb/index.js#L103)

* [Fix in master](https://github.com/Azure/meta-azure-service-broker/blob/master/lib/services/azuremysqldb/index.js#L129) that doesn't use `{your_database}` anymore

**Comment by zhongyi-zhang** [comment]
Hi  @mrbuk ,

Thanks for the reminding! The tag for v1.4.0 was just added. But sorry for not including the change you want:(. I think the release here should keep consistency with the pcf tile.
Please look forward to the next version! The change will be included.

**Comment by mrbuk** [comment]
Thanks for letting me know.
