### ISSUE TITLE
Provide azure-service-bus binder in spring cloud stream

### ISSUE THREAD

**Issue by cforce** [Azure/meta-azure-service-broker#138]
https://github.com/spring-cloud/spring-cloud-stream

**Comment by cforce** [comment]
https://github.com/spring-cloud/spring-cloud-stream/issues/1047

**Comment by bingosummer** [comment]
Thanks @cforce for raising the issue.
Could you please describe roughly what is needed from the broker side? Or the changes are only in spring cloud stream side?

**Comment by cforce** [comment]
I think requirements may pop up by consumer (Spring cloud stream) implementation, if any.
Would be great if ms would send a pull request for a spring cloud stream binder implementation for azure-service-bus.

**Comment by kevinhillinger** [comment]
Recommend closing @zhongyi-zhang @thomas1206 as it's two years old now, and no longer relevant.
