### ISSUE TITLE
Any support for PCF 1.12.* and how about stemcell?

### ISSUE THREAD

**Issue by kamoljan** [Azure/meta-azure-service-broker#150]

**Comment by bingosummer** [comment]
Thanks for raising it. We didn't test the broker in 1.12 because 1.12 is not released when we published the latest version of broker. Will test it next week and keep you posted.

**Comment by kamoljan** [comment]
@bingosummer any update on this issue?

**Comment by bingosummer** [comment]
@kamoljan Sorry for the late response. Yes. 1.12 is supported.
