### ISSUE TITLE
Hdinsight Kafka Brokerage

### ISSUE THREAD

**Issue by cforce** [Azure/meta-azure-service-broker#152]
Provide Broker to HdInsight Kafka Broker for streaming pipelines into data analytics cluster.
https://azure.microsoft.com/en-us/services/hdinsight/apache-kafka/

**Comment by zhongyi-zhang** [comment]
@cforce, thanks for raising this!
In fact, this is in-progress in a developing repo (the successor of this repo). And it will be open source in the end of this month. I'll redirect you to the repo at that time.
Could you share the scenario how does a CF app use Kafka? It would help a lot to implement best practice.

**Comment by cforce** [comment]
You need to put a service broker in front of your cluster, to allow different apps in CF to talk to your kafka on azure. Rather than having to manually tell people the access info each time, they can do cf bind-service SOME_APP AZURE_KAFKA_SERVICE.   hat you have to implement is the Azure kafka service broker (see http://docs.cloudfoundry.org/services/managing-service-brokers.html ). Additionally i would propose a connector to easily allow and output (Sink) for spring cloud stream (https://cloud.spring.io/spring-cloud-stream/) event's which comes out of the idea of an event sourcing architecture (http://cloud.spring.io/spring-cloud-dataflow/) . That shall work out of the box if your broker supports binding https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_apache_kafka_binder.html

There are github projects you can extract idea's howto do this:
* https://github.com/cf-platform-eng/kafka-service-broker
** https://github.com/cf-platform-eng/kafka-service-broker/tree/master/kafka-broker
** https://github.com/cf-platform-eng/kafka-service-broker/tree/master/kafka-connector
* https://github.com/cloudfoundry-community/kafka-service-broker-boshrelease

**Comment by zhongyi-zhang** [comment]
Maybe I didn't ask the question clearly. Actually I wonder what credentials to bind to app and how they are used. Whatever, the kafka-connector repo inspires me. Thanks!

**Comment by kevinhillinger** [comment]
This issue is two years old. Recommend closing @thomas1206
