### ISSUE TITLE
Alerts and monitoring pivotal critical metrics

### ISSUE THREAD

**Issue by kamoljan** [Azure/meta-azure-service-broker#159]
Hi Azure Team!

I was wondering if you have any work done to create alerts for pivotal metrics like this [one] (https://docs.pivotal.io/pivotalcf/1-12/monitoring/kpi.html) ?

Thanks

**Comment by HDYA** [comment]
Hi @kamoljan 

Yes we do. 
We have OMS support with our [Firehose Nozzle](https://github.com/Azure/oms-log-analytics-firehose-nozzle), you can find templates for alerts [here](https://github.com/Azure/azure-quickstart-templates/blob/master/oms-cloudfoundry-solution/nested/omsAlerts.json), you may also find other templates about OMS workspace, views and saved searches there.

By the way, service broker doesn't include monitoring or OMS-related features, did you post the issue to the wrong repo?

Wish you all the best

**Comment by kamoljan** [comment]
@HDYA thank you very much for your prompt response!
And thank you very much for the work you have done!
