### ISSUE TITLE
Creating services on West Europe region times out

### ISSUE THREAD

**Issue by aguedes-pivotal** [Azure/meta-azure-service-broker#163]
Hi,

Using the service broker to create services on the West Europe region often times out. This happens very often while trying to create azure-sqldb instances.

**That's the response I get:**
`Server error, status code: 504, error code: 10001, message: The request to the service broker timed out: https://azure-service-broker.apps.pcfdomain/v2/service_instances/UUID?accepts_incomplete=true`

**This is the log I get from the service broker:**
`warn: [common] msRestRequest : {"statusCode":504,"body":{"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.Sql' within the specified time period."}},"headers":{"cache-control":"no-cache","pragma":"no-cache","content-type":"application/json; charset=utf-8","expires":"-1","x-ms-failure-cause":"service","x-ms-request-id":"","x-ms-correlation-request-id":"","x-ms-routing-request-id":"WESTEUROPE:20171116T135836Z:","strict-transport-security":"max-age=31536000; includeSubDomains","date":"Thu, 16 Nov 2017 13:58:35 GMT","connection":"close","content-length":"141"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"management.azure.com","port":null,"hostname":"management.azure.com","hash":null,"search":"?api-version=2014-04-01-preview","query":"api-version=2014-04-01-preview","pathname":"//subscriptions/X/resourceGroups/azure-service-broker/providers/Microsoft.Sql/servers/XXXX","path":"//subscriptions/X/resourceGroups/azure-service-broker/providers/Microsoft.Sql/servers/XXXX?api-version=2014-04-01-preview","href":"https://management.azure.com//subscriptions/X/resourceGroups/azure-service-broker/providers/Microsoft.Sql/servers/XXXX?api-version=2014-04-01-preview"},"method":"PUT","headers":{"Content-Type":"application/json; charset=UTF-8","Accept":"application/json","x-ms-return-client-request-id":true,"x-ms-client-request-id":"X","Authorization":"Bearer X"`

Maybe making the timeout configurable would be a good idea? Switching it over to a region like East US solves the problem.

**Comment by zhongyi-zhang** [comment]
I also hit it once or twice. And I'm afraid the broker could not help to solve it...
https://github.com/Azure/azure-quickstart-templates/issues/2238
https://stackoverflow.com/questions/42428739/azure-cant-remove-sql-server
See above two pages, the issue could be hit even with azure template and portal.
Code 504 is responded from Azure. And it means that one server did not receive a timely response from another server. So I think it is a SQL Server infrastructure issue.

**Comment by kevinhillinger** [comment]
@zhongyi-zhang @thomas1206 recommend closing this issue. Two years old and no longer relevant.
