### ISSUE TITLE
Redis Cache Service Plan on PCF

### ISSUE THREAD

**Issue by yukikashiwabara** [Azure/meta-azure-service-broker#167]
I could not create Standard services for Azure Redis even I select standard. 
default SKU is created any time when I tried to create it from PCF Apps Manager.

Are there any mean to selectable service plans for Redis Cache?
It looks developer needs to define the SKU every time.

**Comment by zhongyi-zhang** [comment]
Hi @yukikashiwabara, thanks for raising the issue. This is fixed and will be included in the next release. The release date is expected in next week.
