### ISSUE TITLE
<Query> Is this repo deprecated as similar repos are present :[ https://github.com/Azure/open-service-broker-azure ]

### ISSUE THREAD

**Issue by codevulture** [Azure/meta-azure-service-broker#170]
[Azure-osba-repo](https://github.com/Azure/open-service-broker-azure)

**Comment by zhongyi-zhang** [comment]
@codevulture yes, OSBA is the successor of this repo. MASB will be replaced by OSBA over time.

**Comment by codevulture** [comment]
thanks!
