### ISSUE TITLE
Creating multiple database in a single PGSQL cluster

### ISSUE THREAD

**Issue by lakshmantgld** [Azure/meta-azure-service-broker#178]
This is more of a documentation question. 

### Background:
**Platform:** `PCF`
*Microsoft Azure Service Broker:* `v1.5.2`
All apps in a given space use the same PGSQL instance/cluster.

### Problem:
- All the apps use the same `username`, `database` to connect to the cluster. I would like to create a separate username & database for each `CF application` connected to the cluster. Is that possible?
- What is the definition of `Basic50`, `Basic100` plans in PCF? I don't see proper docs on the plans shown in the PCF, whereas in Azure portal I just see Basic, standard and premium plan. I don't understand the connection between these two. Insight on that would be great.

**Comment by zhongyi-zhang** [comment]
@lakshmantgld thanks for the feedback and I am really sorry for the long delayed response...

>* All the apps use the same username, database to connect to the cluster. I would like to create a separate username & database for each CF application connected to the cluster. Is that possible?

MASB is in maintenance mode now. So this feature might not be added, in principle. As the successor of MASB, PostgreSQL and MySQL in [OSBA](https://github.com/Azure/open-service-broker-azure) implemented that different users are delivered in different bindings. Welcome to OSBA!

>* What is the definition of `Basic50`, `Basic100` plans in PCF? I don't see proper docs on the plans shown in the PCF, whereas in Azure portal I just see Basic, standard and premium plan. I don't understand the connection between these two. Insight on that would be great.

The numbers indicate DTUs. The pricing model based on DTUs are deprecated in Azure PostgreSQL / MySQL now. FYI: https://azure.microsoft.com/en-us/pricing/details/postgresql/. OSBA is updated with the new model.

**Comment by kevinhillinger** [comment]
OSBA is no longer supported. @zhongyi-zhang recommend either placing in the maintenance project or closing this issue.
