### ISSUE TITLE
Example for blob service could be improved

### ISSUE THREAD

**Issue by CraigWiand** [Azure/meta-azure-service-broker#19]
https://github.com/Azure/meta-azure-service-broker/blob/master/docs/azure-storage-blob.md#create-an-azure-storage-blob-service

Per the installation instructions:
  ```
  cf create-service azurestorageblob default myblobservice -c examples/storageblob-example-config.json
  ```
should really be:
  ```
  cf create-service azure-storageblob standard myblobservice -c examples/storageblob-example-config.json
  ```

**Comment by bingosummer** [comment]
Thanks @CraigWiand .
Fixed in 2344051965bf1f754f856bf779e61641c47c4792
