### ISSUE TITLE
Example for using azure storage client needs to incude step to modify service name

### ISSUE THREAD

**Issue by CraigWiand** [Azure/meta-azure-service-broker#20]
https://github.com/Azure/meta-azure-service-broker/blob/master/docs/azure-storage-blob.md#binding
 Step 1 instructs to just build and push.  If you follow the previous examples you will get a failure to start the application.  In the logs you will see:

> 2016-08-30T15:55:20.01+0000 [APP/0]      ERR Traceback (most recent call last):
> 2016-08-30T15:55:20.01+0000 [APP/0]      ERR   File "demo.py", line 15, in <module>
> 2016-08-30T15:55:20.01+0000 [APP/0]      ERR     account_name = vcap_services[service_name][0]['credentials']['storage_account_name']
> 2016-08-30T15:55:20.01+0000 [APP/0]      ERR KeyError: 'azurestorageblob'

This is because the service name is hard coded in the sample app as `azurestorageblob` but in the examples in the walkthrough the name used is `azure-storageblob` with a hypen.

Please update to either:
- change the sample code [here ](https://github.com/bingosummer/azure-storage-consumer/blob/master/demo.py#L13)to include the hyphen 
- include a step in the walkthrough to change 
- change the walkthrough to use `azurestorageblob`

**Comment by bingosummer** [comment]
Thanks @CraigWiand for reporting this. I also find this issue when I walkthrough the doc yesterday and It's fixed now.
