### ISSUE TITLE
cf enable-service-access azure-postgresqldb is not work

### ISSUE THREAD

**Issue by keliangneu** [Azure/meta-azure-service-broker#203]
Hello,

I'm use azure service broker 1.10.1 and PCF 2.2, when I run cf marketplace command I cannot find azure-postgresqldb, then I run command: cf enable-service-access azure-postgresqldb, it returns "$ cf enable-service-access azure-postgresqldb
Enabling access to all plans of service azure-postgresqldb for all orgs as admin...
FAILED
Service offering azure-postgresqldb not found"

**Comment by David-Pivotal** [comment]
@zhongyi-zhang Thanks for checking. Please be noted this issue happens in Azure China. So could you please have a check in Azure China?

**Comment by zhongyi-zhang** [comment]
Oh, thanks for the hint. I'll have a try.

**Comment by zhongyi-zhang** [comment]
@David-Pivotal ah, I remind that it is so in Azure China. When the service broker adding PostgreSQL service module, it was still Preview and only Preview in Azure Public Cloud. So we didn't expose it to the catalog when the environment is Azure China (or Azure Germany / Azure US Gov). Since this repo got into maintenance mode, we didn't continue catching up with the public cloud GA or sovereign clouds GA.

**Comment by David-Pivotal** [comment]
@zhongyi-zhang Thanks for your help!

**Comment by David-Pivotal** [comment]
@keliangneu both postgres db and mysql db are not supported in Azure China as per link https://github.com/Azure/meta-azure-service-broker/blob/master/docs/how-admin-deploy-the-broker.md#deploy-the-meta-azure-service-broker-as-an-application-in-cloud-foundry.

**Comment by zhongyi-zhang** [comment]
@David-Pivotal they are supported in Azure China but not in this service broker...

**Comment by keliangneu** [comment]
@zhongyi-zhang @David-Pivotal  Thanks for your help. Since it's not support azure China for the moment, is there any workaround?  and do you know the ETA of azure China?

**Comment by NingKuang** [comment]
@keliangneu Thank you for the feedback, could you share a little more background for this request? Do you plan to use MSBA for production or testing, what is your schedule? Feel free to email us (azcfengg@microsoft.com) the details, that will help us finalize the priority.
