### ISSUE TITLE
enable TDE parameter for SQL DB in json parameters file

### ISSUE THREAD

**Issue by chomipi** [Azure/meta-azure-service-broker#24]
We have a requirement to enable TDE (Transparent Data Encryption) on the SQL DBs that are created using the service broker. Can you add a parameter/flag to have this enabled at DB creation time?

**Comment by niroyb** [comment]
I'll work on this, here is a task breakdown:
- [ ] Extend [examples/sqldb-example-config.json](../blob/master/examples/sqldb-example-config.json) schema
- [ ] Update [azure-sql-db.md](../blob/master/docs/azure-sql-db.md) with new option
- [ ] Implement [TDE api](https://docs.microsoft.com/en-us/rest/api/sql/databases#Databases_CreateOrUpdateTransparentDataEncryptionConfiguration)
- [ ] Add tests
