### ISSUE TITLE
unify the name and parameters for each service

### ISSUE THREAD

**Issue by bingosummer** [Azure/meta-azure-service-broker#4]
1. Some service name begins with `azure`, and some doesn't. Please unify the names.
2. The same parameters such as `resource_group_name` are using in several brokers when provisioning a service, but they have different name (resource_group_name, resourceGroupName). Please unify these parameters so as not to confuse users.

**Comment by sebastus** [comment]
1. I assume you mean in the service.json.  I updated the doc db service description to "Azure DocumentDb Service".
2. In what context?  And which spelling do you prefer?

**Comment by bingosummer** [comment]
1. For example, https://github.com/Azure/meta-azure-service-broker/blob/master/lib/services/azurerediscache/service.json#L3. The name is `RedisCacheService` which may be confused with the community or pivotal redis service.
2. In the parameters file for each service, the parameter names are different in the format. I prefer `resource_group_name`.

Don't worry. I will update all of them. This issue is just a reminder.

**Comment by zhongyi-zhang** [comment]
resolved by https://github.com/Azure/meta-azure-service-broker/pull/122
