### ISSUE TITLE
Deprecated package warnings during npm install

### ISSUE THREAD

**Issue by niroyb** [Azure/meta-azure-service-broker#68]
Running `npm install` on a fresh system yields these warnings:
```
meta-azure-service-broker>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.2.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```

**Comment by bingosummer** [comment]
@niroyb 
Only `node-uuid@1.4.7` is installed directly in [package.json](https://github.com/Azure/meta-azure-service-broker/blob/master/package.json#L38). `tough-cookie@2.2.2` and etc. are dependencies of other packages. So if other packages do not update them to the new versions, we will still have these warnings.
At this point, what we can do is to upgrade `node-uuid@1.4.7` to `uuid@3.0.0` if there are no breaking changes. Are you interested in this change?

FYI: https://github.com/kelektiv/node-uuid/issues/142

**Comment by niroyb** [comment]
If there are no breaking changes and it fixes issues from the deprecated dependencies then we should definitely upgrade.
