### ISSUE TITLE
Configuration parameter name Azure resource group is not consistent

### ISSUE THREAD

**Issue by mdcarlson** [Azure/meta-azure-service-broker#75]
The name of the parameter used to provide the name of the Azure resource group is not consistent.

The name is _resourceGroup_ for 
- Redis Cache
- DocumentDB
- SQLDb

The name is _resource_group_name_ for 
- Storage
- Service Bus

Could a consistent name be used?  This will help as more services get added in the future.

Mark

**Comment by zhongyi-zhang** [comment]
resolved by https://github.com/Azure/meta-azure-service-broker/pull/122
