### ISSUE TITLE
Deleting a sql db service does not delete the appropriate sql server on azure

### ISSUE THREAD

**Issue by nsagoo-pivotal** [Azure/meta-azure-service-broker#83]
While we are allowed to provision new sql serves and new sql databases using the broker, when a delete-service command is issue, it appears that the sql database is deleted but the server continues to stay active. Why does this happen? Should a user be able to create and delete both databases and sql servers on demand without using the portal? 

E.g. 

▶ cf ds afcea-sql-server -f
Deleting service afcea-sql-server in org afcea-west / space usmc as admin...
OK

Delete in progress. Use 'cf services' or 'cf service afcea-sql-server' to check operation status.

When I go into the Microsoft Azure portal, I am able to see the database and server that I asked to be deleted from cloud foundry. 

STATUS
Available
SERVER NAME
afcea-sql-server.database.windows.net

**Comment by bingosummer** [comment]
Yes. The behavior is expected. Even if it's allowed to create a new sql server, there is a possibility that the user creates multiple databases in a shared sql server. Considering this case, the broker don't delete the sql server when one of the databases is deleted.
