### ISSUE TITLE
Make deployable to Kubernetes

### ISSUE THREAD

**Issue by krancour** [Azure/meta-azure-service-broker#96]
The [kubernetes-incubator/service-catalog](https://github.com/kubernetes-incubator/service-catalog) adapts OSB brokers to a k8s-native workflow. i.e. It allows off-cluster, managed services (like those managed by this broker) to be provisioned and bound by creating k8s resources.

The docs in this repo assume the operator is deloying to CF, but if there is any other aspect of this broker that couples it to CF-only, it's not immediately evident to me. It seems that with the addition of a Dockerfile and a Helm chart, this could be easily deployable to a Kubernetes cluster instead, where the service-catalog and this broker could be used as an on-ramp to Azure services.

**Comment by krancour** [comment]
@niroyb it looks like you're an admin for this repo. Could you possibly assign this issue to me to avoid the potential for duplicate efforts?

**Comment by bingosummer** [comment]
Thanks @krancour for the proposal. It's great if you can submit a PR to support deploying in k8s.
If you could provide some guidance for how to deploy it, then we can help verify the PR from our side.

**Comment by krancour** [comment]
I'm going to back off of this a little bit... I really just want to get this Dockerized instead. (Will open a new issue for that.) Deployment to k8s can be handled by the addition of the chart to [kubernetes/charts](https://github.com/kubernetes/charts) instead. That is a better and more strategic home for all such charts anyway.
